server:
  port: 8881
  address: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: hello-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer1:1112/eureka/
  instance:
    preferIpAddress: true