spring:
  peer1
  application:
    name: peer1
  profiles:
    active: peer1
eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
  server:
    enable-self-preservation: false
server:
  port: 1111