spring:
  application:
    name: peer2
  profiles:
    active: peer2
eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
  server:
    enable-self-preservation: false
server:
  port: 1112